### ISSUE TITLE
It takes two requests to create a customer or card

### ISSUE THREAD

**Issue by mcampa** [balanced/balanced-php#122]
It takes two requests to create a customer or card, with the current php library.

This is what the documents show on how to create a `Customer`

``` php
$marketplace = Balanced\Marketplace::mine();
$customer = $marketplace->customers->create($params);
```

This takes two requests, and it is extremely slow to fetch the `marketplace`. It's taking almost 6 seconds.

But when I switch to CURL I see that I can create a customer with one request.

So, how do I create a customer with one request?

**Comment by mjallday** [comment]
What happens if you run 

``` php
$customer = new Customer();
$customer->save();
```

**Comment by mcampa** [comment]
Wow, so simple, but the documentation so convoluted.

Instead of having this in the docs:

``` php
$marketplace = Balanced\Marketplace::mine();
$customer = $marketplace->customers->create(array(
  'address' => array( 
     'postal_code' => '48120', 
  ), 
  'dob_month' => '7',
  'dob_year' => '1963',
  'name' => 'Henry Ford',
));
```

You could rewrite that to:

``` php
$customer = new Balanced\Customer(array(
  'address' => array( 
     'postal_code' => '48120', 
  ), 
  'dob_month' => '7',
  'dob_year' => '1963',
  'name' => 'Henry Ford',
));

$customer->save();
```

It's not obvious. Anybody reading the docs could think that it needs the `$marketplace` to create a `Customer`

**Comment by mjallday** [comment]
Yup, you're right, it should be much simpler. I've opened another issue (#123) to resolve this. I'm going to close this one out, thanks for bringing this to our attention.

[EDIT] For the record, this is a legacy from the previous revision which required posting to a nested URL which was under the marketplace e.g. `/marketplaces/MP123123/customers`
