### ISSUE TITLE
Consider dropping php-5.x versions

### ISSUE THREAD

**Issue by peter279k** [balanced/balanced-php#124]
As title, since the `php-7.0` version has been released for whiles.

And I think it's time to drop `php-5.x` versions and upgrade this repository to `php-7.x` now :).

And the PHPUnit version should be upgraded, too.

Once this issue is accepted, I can work on this :).

**Comment by msherry** [comment]
This company has been out of business for some time, so there is little need to work on this issue :)

**Comment by peter279k** [comment]
Hi @msherry, thanks for your reply.

That's right. The service seems to be unavailable now.

Closed.
